name: media_upload
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  image_picker: ^0.8.7+5
  dio: ^5.4.0
  sembast: ^3.5.0
  path_provider: ^2.0.14
  uuid: ^3.0.7
  connectivity_plus: ^5.0.2
  file_picker: ^5.3.1
  mime: ^1.0.5
  flutter_riverpod: ^2.5.1
  flutter_foreground_task: ^9.1.0
  flutter_svg: ^2.0.16
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6
  cached_network_image: ^3.3.1
  pool: ^1.5.1
  flutter_video_info: ^1.3.3







dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
